_core:
  default_config_hash: 9bVDfWSa_In6VzTXmy04jJ_3ZQobihKjO9isuuUCPaw
protect_all_forms: false
unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
log: true
element_name: grg234dvv
time_limit: 6
expire: 300
form_settings:
  user_register_form: true
  user_pass: false
  contact_message_feedback_form: false
  contact_message_personal_form: false
  node_advertisement_form: false
  node_article_form: false
  node_associate_member_form: false
  node_column_form: false
  node_community_updates_form: false
  node_fillable_forms_form: false
  node_marquee_promotion_form: false
  node_page_form: false
  node_webform_form: false
  comment_comment_form: false
