_core:
  default_config_hash: 8rlYgCTun_RhG0h4IrQ4AgYkOemlvLqaVN8Su1UdPaU
favicon:
  use_default: true
features:
  comment_user_picture: true
  favicon: true
  node_user_picture: true
zurb_foundation_status_in_reveal: false
zurb_foundation_disable_base_css: false
zurb_foundation_disable_base_js: false
zurb_foundation_meta_header_grid: true
zurb_foundation_top_bar_enable: 1
zurb_foundation_top_bar_grid: false
zurb_foundation_top_bar_sticky: true
zurb_foundation_top_bar_menu_text: Menu
zurb_foundation_top_bar_custom_back_text: true
zurb_foundation_top_bar_back_text: Back
zurb_foundation_top_bar_is_hover: true
zurb_foundation_top_bar_search: false
zurb_foundation_top_bar_languageswitcher: false
zurb_foundation_block_copyright_show: false
zurb_foundation_block_copyright_custom_text: false
zurb_foundation_block_copyright_text: ''
